### ISSUE TITLE
not install form composer

### ISSUE THREAD

**Issue by IgorVBelousov** [phpDocumentor/template.zend#27]
```
- phpdocumentor/template-zend 1.3.2 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
- phpdocumentor/template-zend 1.3.1 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
- phpdocumentor/template-zend 1.3.0 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
```

**Comment by mvriel** [comment]
Hello @IgorVBelousov,

Those messages mean that the [XSL extension](http://php.net/manual/en/book.xsl.php) of PHP is not installed on your host. This extension is required to generate HTML templates from an XML source file.

You can resolve this error by installing the XSL extension for PHP.

**Comment by IgorVBelousov** [comment]
Tnx for help
